/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'STM32F7_BOOT' 
 * Target:  'STM32F7_BOOT' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* ARM::CMSIS-Compiler:STDOUT:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Custom         /* CMSIS-Compiler STDOUT: Custom */


#endif /* RTE_COMPONENTS_H */
