/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.0.0
 *
 * Project: 'STM32F103_APP' 
 * Target:  'STM32F103_APP' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* kk::MicroBoot:components:check_agent_engine@1.0.0 */
#define __USER_APP_CFG_H__ "user_app_cfg.h"
/* kk::MicroBoot:components:multiple_delay@1.0.0 */
#define __USER_APP_CFG_H__ "user_app_cfg.h"
/* kk::MicroBoot:components:queue@1.0.0 */
#define __USER_APP_CFG_H__ "user_app_cfg.h"
/* kk::MicroBoot:components:shell@1.0.0 */
#define __USER_APP_CFG_H__ "user_app_cfg.h"


#endif /* PRE_INCLUDE_GLOBAL_H */
