/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'stm32f103boot' 
 * Target:  'stm32f103boot' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* kk::MicroBoot:components:Bootloader@0.9.6 */
#define __USER_APP_CFG_H__ "user_app_cfg.h"
/* kk::MicroBoot:components:FlashDrv&STM32@0.9.6 */
#define __USER_APP_CFG_H__ "user_app_cfg.h"
/* kk::MicroBoot:components:check_agent_engine@0.9.6 */
#define __USER_APP_CFG_H__ "user_app_cfg.h"
/* kk::MicroBoot:components:queue@0.9.6 */
#define __USER_APP_CFG_H__ "user_app_cfg.h"
/* kk::MicroBoot:components:shell@0.9.7 */
#define __USER_APP_CFG_H__ "user_app_cfg.h"
/* kk::MicroBoot:components:signals_slots@0.9.6 */
#define __USER_APP_CFG_H__ "user_app_cfg.h"
/* kk::MicroBoot:components:subscribe_publish@0.9.6 */
#define __USER_APP_CFG_H__ "user_app_cfg.h"
/* kk::MicroBoot:components:ymodem@0.9.6 */
#define __USER_APP_CFG_H__ "user_app_cfg.h"


#endif /* PRE_INCLUDE_GLOBAL_H */
