/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.0.0
 *
 * Project: 'stm32f103boot' 
 * Target:  'stm32f103boot' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* kk::MicroBoot:components:Bootloader@1.0.0 */
#define __USER_APP_CFG_H__ "user_app_cfg.h"
/* kk::MicroBoot:components:FlashDrv&STM32@1.0.0 */
#define __USER_APP_CFG_H__ "user_app_cfg.h"
#define __FLASH_CFG_PORTING_INCLUDE__ "flash_port_user.h"
/* kk::MicroBoot:components:check_agent_engine@1.0.0 */
#define __USER_APP_CFG_H__ "user_app_cfg.h"
/* kk::MicroBoot:components:multiple_delay@1.0.0 */
#define __USER_APP_CFG_H__ "user_app_cfg.h"
/* kk::MicroBoot:components:queue@1.0.0 */
#define __USER_APP_CFG_H__ "user_app_cfg.h"
/* kk::MicroBoot:components:shell@1.0.0 */
#define __USER_APP_CFG_H__ "user_app_cfg.h"
/* kk::MicroBoot:components:signals_slots@1.0.0 */
#define __USER_APP_CFG_H__ "user_app_cfg.h"
/* kk::MicroBoot:components:subscribe_publish@1.0.0 */
#define __USER_APP_CFG_H__ "user_app_cfg.h"
/* kk::MicroBoot:components:ymodem@1.0.0 */
#define __USER_APP_CFG_H__ "user_app_cfg.h"


#endif /* PRE_INCLUDE_GLOBAL_H */
